products = [
  {
    '_id': "1",
    'name': "Aurpods Wireless Bluethood Headphones",
    'image': "/images/airpods.jpg",
    'description': "Audifonos modernos de apple para escuchar musica con calidad",
    'brand': "Apple",
    'category': "Electronics",
    'price': 89.99,
    'countInStock': 10,
    'rating': 3.5,
    'numReviews': 12,
  },
  {
    '_id': "2",
    'name': "Imphone 12",
    'image': "/images/phone.jpg",
    'description': "Penultimo modelo de apple para los telefonos",
    'brand': "Apple",
    'category': "Electronics",
    'price': 999.99,
    'countInStock': 5,
    'rating': 1.5,
    'numReviews': 10,
  },
  {
    '_id': "3",
    'name': "Camara extrema",
    'image': "/images/camera.jpg",
    'description': "Camara de ultima calidad",
    'brand': "Etecsa",
    'category': "Electronics",
    'price': 200.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': "4",
    'name': "Playstation 5",
    'image': "/images/playstation.jpg",
    'description': "Ultimo modelo de Microsoft para consolas de videojuegos",
    'brand': "AMicrosoft",
    'category': "Electronics",
    'price': 500.99,
    'countInStock': 10,
    'rating': 1.5,
    'numReviews': 12,
  },
  {
    '_id': "5",
    'name': "Mouse gaming",
    'image': "/images/mouse.jpg",
    'description': "Mouse gaming para jugar Rainbow",
    'brand': "Etecsa",
    'category': "Electronics",
    'price': 30.99,
    'countInStock': 10,
    'rating': 3.5,
    'numReviews': 12,
  },
  {
    '_id': "6",
    'name': "Bocina de musica",
    'image': "/images/alexa.jpg",
    'description': "Algo que se llama alexa",
    'brand': "Etecsa",
    'category': "Electronics",
    'price': 30.99,
    'countInStock': 10,
    'rating': 2,
    'numReviews': 12,
  },
];
