# Generated by Django 3.1.7 on 2021-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210416_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
